using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class AssemblerButton : MonoBehaviour
{
    /// <summary>
    /// The item being generated by this button.
    /// </summary>
    [SerializeField] private GameObject item;

    /// <summary>
    /// The normal button sprite.
    /// </summary>
    [SerializeField] private Sprite normalImage;
    
    /// <summary>
    /// The corrupted button sprite.
    /// </summary>
    [SerializeField] private Sprite corruptedImage;

    /// <summary>
    /// Subscribe to GameEvents.
    /// </summary>
    void Awake()
    {
        GameEvent.OnOrderComplete += UpdateButtons;
    }

    /// <summary>
    /// Updates the sprite of the button to be corrupted if the item is not usable.
    /// </summary>
    private void UpdateButtons()
    {
        // todo: test
        GetComponent<Image>().sprite = item.GetComponent<Ingredient>().CanUse() ? normalImage : corruptedImage;
        GetComponent<Button>().interactable = item.GetComponent<Ingredient>().CanUse();
    }

    /// <summary>
    /// Unsubscribes from GameEvents.
    /// </summary>
    void OnDestroy()
    {
        GameEvent.OnOrderComplete -= UpdateButtons;
    }
}