using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class AssemblerButton : MonoBehaviour
{
    /// <summary>
    /// The item being generated by this button.
    /// </summary>
    [SerializeField] private GameObject item;

    /// <summary>
    /// The normal button sprite.
    /// </summary>
    [SerializeField] private Image normalImage;
    
    /// <summary>
    /// The corrupted button sprite.
    /// </summary>
    [SerializeField] private Image corruptedImage;
    
    /// <summary>
    /// Whether the item can be used or not.
    /// </summary>
    private bool _canUse = true;

    /// <summary>
    /// 
    /// </summary>
    void Awake()
    {
        // todo make an event to check if player can use this item. if not, render different button
    }
}